### ISSUE TITLE
Don't output tuples that are satisfiable and have no inferred annotations

### ISSUE THREAD

**Issue by balhoff** [geneontology/gaferencer#2]
@dougli1sqrd @cmungall would this make sense? It would make the output files smaller. Is there any point to output all results?

**Comment by cmungall** [comment]
Yes it makes sense. I think I had this sort of in mind in the first place. The output should be only new entailments

**Comment by balhoff** [comment]
Fixed in 2526d592b1b42cc5b8017385d09fa0f00dc4f5f3.
