### ISSUE TITLE
Context file keys could be Case insensitive

### ISSUE THREAD

**Issue by dougli1sqrd** [geneontology/gaferencer#3]
When resolving GAF IDs against the context, sometimes the GAF use different capitalization methods. So they are not found in the context files, even if they are technically present. For example, wormbase has some IDs with prefixes of `WBbt` and `ChEBI` which obviously correspond to `WBBT` and `CHEBI` respectively. 

If gaferencer assumed that WBbt mapped to WBBT, we would be golden I think. Unless that's not desired.

@cmungall Do you have any opinions on this?

**Comment by cmungall** [comment]
There is exactly one canonical form for each ontology. 

The obo context was incorrect for WBbt, this fixes:
https://github.com/OBOFoundry/OBOFoundry.github.io/pull/713

**Comment by balhoff** [comment]
It sounds like they should remain case sensitive. Let me know if you disagree.
